### ISSUE TITLE
Instruções para arrancar com a sala

### ISSUE THREAD

**Issue by 4345dgfsd** [Coletinn/haxball-bot-typescript#1]
A

**Comment by 4345dgfsd** [comment]
Id like a response please.

**Comment by 4345dgfsd** [comment]
Id like a response on how to start this script.

**Comment by Coletinn** [comment]
Hello. You need to create a .env file with the variables:

DB_HOST=
DB_USER=
DB_PASSWORD=
DB_DATABASE=
DISCORDTOKEN=
maxTeamSize=
maxGoals=
timeLimit=
room_id=
public=
# debug=1
mapa=
TOKEN=

**Comment by 4345dgfsd** [comment]
Hi, thank you very much for your response, id like to ask another question though. I would like to ask if you could clarify this a bit more. (room_id=
public=
mapa=) 
Especially the room_id, and mapa.

Once again, thank you so much for your response <3

**Comment by Coletinn** [comment]
room_id is a number, can be like 1, 2, 3, etc. For my project here its useful to recognize the game modes. For example, room_id = 1 means for Futsal x3 game mode. room_id = 2 means for Futsal x4 game mode, room_id = 3 means for Volleyball mode.

public is for if you want to set your room public or not, if it is 1, will appear in the Haxball room list. If 0, won't be public, thus it won't appear in Haxball room list.

mapa is which map you want to set, in this project the maps are stored in the stadiums folder.

OBS: If you want to talk in portuguese we can talk in Portuguese, im Brazilian.

Thanks.

**Comment by 4345dgfsd** [comment]
Hi, thank you for your response. Im glad you responded. I actually dont speak portuguese, but i just use google translate. Once again, thanks a lot <3

**Comment by 4345dgfsd** [comment]
Hi again, so just a question about the "mapa=" line, if i want to use the given maps, what would i have to put there?
Thanks.

**Comment by Coletinn** [comment]
Just put the name of the map in the stadiums folder, example: if the map is Bazinga.hbs, just put Bazinga

**Comment by 4345dgfsd** [comment]
Ah, okay. Thank you very much.

**Comment by 4345dgfsd** [comment]
Hi there, i'm trying to get the room working, when i run instalar.bat, i get a bunch of errors. i'd like to share my error log and see if there is possibly a solution to this, either something is missing on my pc, but i'm not sure. 
[2024-08-09T21_18_33_232Z-debug-0.log](https://github.com/user-attachments/files/16566984/2024-08-09T21_18_33_232Z-debug-0.log)

The errors start from line 1308 in the .log file.

Thanks.
